version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - pytorch
        - tensorflow
  system_packages: true

sphinx:
  fail_on_warning: true